# Generated by Django 4.0.3 on 2022-03-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.URLField(max_length=250)),
                ('contract', models.BooleanField()),
                ('budget', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('live', models.CharField(max_length=15)),
                ('profile_image', models.URLField(max_length=250)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.company')),
            ],
            options={
                'db_table': 'influencers',
            },
        ),
        migrations.CreateModel(
            name='InfluencerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=250)),
                ('created_at', models.DateTimeField(null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insight.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.influencer')),
            ],
            options={
                'db_table': 'influencer_posts',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'social_network_services',
            },
        ),
        migrations.CreateModel(
            name='Snsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField()),
                ('url', models.URLField(max_length=250)),
                ('created_at', models.DateTimeField(null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.influencer')),
                ('social_network_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.socialnetworkservice')),
            ],
            options={
                'db_table': 'sns_infos',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.company')),
            ],
            options={
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_frequency', models.IntegerField()),
                ('visit_frequency', models.IntegerField()),
                ('like', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('male_follower', models.IntegerField()),
                ('female_follower', models.IntegerField()),
                ('bookmark', models.IntegerField()),
                ('exposure', models.IntegerField()),
                ('profile', models.IntegerField()),
                ('profile_visit', models.IntegerField()),
                ('website_click', models.IntegerField()),
                ('hashtag', models.IntegerField()),
                ('reaction', models.IntegerField()),
                ('home', models.IntegerField()),
                ('official_visit', models.IntegerField()),
                ('official_follower', models.IntegerField()),
                ('official_referrer', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.influencer')),
                ('influencer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.influencerpost')),
            ],
            options={
                'db_table': 'insights',
            },
        ),
    ]
